### ISSUE TITLE
Error ignoring

### ISSUE THREAD

**Issue by andrew-aladev** [marten-de-vries/pouchdb-size#22]
What was the reason to ignore [error](https://github.com/pouchdb/pouchdb-size/blob/master/index.js#L39)? User is expecting a rejected promise if we couldn't get the disk size.

**Comment by marten-de-vries** [comment]
The reason is that this library is used in pouchdb-server (through express-pouchdb), which in turn can be used with a wide array of storage backends. Some of them might not be compatible with pouchdb-size, which would cause it to crash in some unknown way. If that is the case, we don't want to brake GET /dbname/_info . In short, it's a compromise for those users that see db size info as a nice extra, but not as a requirement. If you really need the db size, you can use the dedicated function of the plug-in. At least, that's the reasoning.

**Comment by andrew-aladev** [comment]
Yes, ok. We will use this function directly.
